name: CloudResearchWorkShop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - ase
  - matplotlib
  - numpy
  - pandas
  - pip
  - pip:
      - torch
      - mace-torch
